# Generated by Django 3.1.3 on 2020-11-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201115_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='color',
            old_name='price',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='price',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='friendly_name',
            new_name='measurement',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
